language: cpp
before_install:
 - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
 - sudo apt-get update -qq
 - sudo apt-get install -qq libqt4-dev libdmtx-dev
compiler:
  - gcc
  - clang
script:
  - lrelease */*/*.ts */*.ts
  - USE_SYSTEM_DMTX=1 BUILD_SHARED_LIBS=1 qmake
  - USE_SYSTEM_DMTX=1 BUILD_SHARED_LIBS=1 make

